language: node_js
sudo: false
node_js:
  - "5"
  - "4"
services:
  - mongodb
before_script:
  ./node_modules/.bin/m ${MONGODB_VERSION}
after_script:
  ./node_modules/.bin/m kill
env:
  - MONGODB_VERSION=3.2.x
